import type { Metadata } from 'next'
import './globals.css'
import FloatButton from "@/components/FloatButton";
import {Providers} from "@/app/providers";
import Message from "@/components/Message";
import Notice from "@/components/notice/Notice";
import './style.css'

export const metadata: Metadata = {
  title: '学习随记',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="zh" suppressHydrationWarning>
      <body>
      <Providers themeProps={{ attribute: "class", defaultTheme: "auto"}}>
        {children}
        <Message/>
        <FloatButton/>
          <Notice/>
      </Providers>
      </body>
      </html>
  )
}
